### ISSUE TITLE
Support for the `vary` header?

### ISSUE THREAD

**Issue by hsablonniere** [natemoo-re/ultrafetch#5]
Hey Nate,

Thanks again for this project :+1:

I just tried it and looked at the code. It seems like you don't support the `vary` header.

* Is it on purpose?
* Do you want to support it?
* Would you like help on this?

Cheers.

**Comment by natemoo-re** [comment]
Hey @hsablonniere! It's definitely not an intentional limitation. `ultrafetch` is basically some glue to combine `fetch` with the [`http-cache-semantics`](https://github.com/kornelski/http-cache-semantics) package, so I'd direct your questions there. 

Interestingly, it does look like support for the `vary` header was [implemented](https://github.com/kornelski/http-cache-semantics#implemented), so maybe there's something else going on?

**Comment by hsablonniere** [comment]
Yes, [`http-cache-semantics`](https://github.com/kornelski/http-cache-semantics) implemented `vary`, I looked at the code and it seems nice. The thing is, if `vary` is used, the headers specified with it must be part of the cache key, and this part is in `ultrafetch` code. I'll see if I can try something in the next fews days/weeks. I'll keep you updated :wink:

**Comment by hsablonniere** [comment]
@natemoo-re Update: I've been digging at how nginx and apache do it. I'm still confused by some details on how nginx does it but I have enough to try an implementation for ultrafetch ;-)

**Comment by hsablonniere** [comment]
Interesting discovery: Chromium has a bug with the Cache API and cannot store multiple versions of the same URL.

https://bugs.chromium.org/p/chromium/issues/detail?id=756796

**Comment by natemoo-re** [comment]
Support for the `Vary` header as a cache key has been released in [`ultrafetch@0.4.0`](https://github.com/natemoo-re/ultrafetch/pull/9)

**Comment by hsablonniere** [comment]
@natemoo-re wow you rock!!! I had zero time to go into it sorry :-( I'll give you a sign if I have time to test it. Thanks ;-)
